# Generated by Django 4.2 on 2024-04-09 05:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_post_p'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P',
            new_name='Post',
        ),
    ]
